/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  printWidth: 100,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@local/(.*)$",
    "^@/api/(.*)$",
    "^@/components/(.*)$",
    "^@/config/(.*)$",
    "^@/constant/(.*)$",
    "^@/data/(.*)$",
    "^@/emails/(.*)$",
    "^@/hooks/(.*)$",
    "^@/layouts/(.*)$",
    "^@/lib/(.*)$",
    "^@/schemas/(.*)$",
    "^@/templates/(.*)$",
    "^@/theme/(.*)$",
    "^@/utils/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
